---
title: "Reproducible Document"
author: "rostools"
format: html
---

```{r setup}
#| message: false
#| warning: false

library(tidyverse)

post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
```


## Writing R code

2 + 2

```{r}
2 + 2
```

## About me
- Aksayan 
- Arunanthy 
- Mahalingasivam

Jeg er til **R** *kursus*

## Simple code
```{r}
3*3
```

Færdig 

**Testing for GIT

Færdig test

##Showin the data
```{r}
post_meal_data

glimpse(post_meal_data)
```

##Plot one continous variable
```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data,aes(x = BMI))+
  geom_histogram()
```

See @fig-bmi-histo

## Exercise: discrete plots
```{r}
#| fig-cap: "glykemi distribution"
#| label: fig-glykemi-distribution
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

See @fig-glykemi-distribution above for a cool plot!

## Plotting two discrete variables
```{r}
ggplot(post_meal_data,aes(x=Group,fill=as.character(glykemi)))+
  geom_bar(position = position_dodge())
```

